In [1]:
import pandas as pd

In [2]:
tabela = pd.read_csv("/home/juniorsilvadev/engenharia-dados/python-etl/Origem/Origem/arquivos_csv/Clientes.csv", delimiter=',')
tabela.head()

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12

In [3]:
tabela = tabela.loc[tabela['state'] == 'São Paulo']

In [4]:
tabela

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
20,20,2017-12-22 10:51:28,Adalberto,Silva,adalberto@usuario.com,9 1338-1447,Brasil,São Paulo,Rua 57 do Estado São Paulo,851.0,Conjunto 20
59,59,2017-12-03 16:24:32,Stephanie,Freire,stephanie@usuario.com,9 3256-1853,Brasil,São Paulo,Rua 52 do Estado São Paulo,34.0,Apto 24
78,78,2017-11-02 22:13:22,Laura,Queiroz,laura@exemplo.com,9 6338-8617,Brasil,São Paulo,Praça 19 do Estado São Paulo,878.0,Conjunto 3

In [ ]:
estado = tabela.loc[tabela['state'] == 'Mato Grosso']

In [ ]:
estado

In [4]:
estados = ['São Paulo', 'Mato Grosso', 'Ceará']
df_estados = tabela.loc[tabela['state'].isin(estados)]
df_estados

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
12,12,2018-03-28 00:24:00,Carol,Barboza,carol@exemplo.com,9 8487-3501,Brasil,Mato Grosso,Rua 31 do Estado Mato Grosso,1.0,Conjunto 23
15,15,2018-11-15 18:00:53,Stephanie,Barbosa,stephanie@usuario.com,9 1446-3560,Brasil,Mato Grosso,NaN,NaN,Conjunto 4
20,20,2017-12-22 10:51:28,Adalberto,Silva,adalberto@usuario.com,9 1338-1447,Brasil,São Paulo,Rua 57 do Estado São Paulo,851.0,Conjunto 20
24,24,2018-07-25 09:34:12,Jair,Barroso,jair@teste.com,9 6679-6120,Brasil,Ceará,Rua 86 do Estado Ceará,770.0,Apto 21
48,48,2018-05-29 04:22:54,Clarissa,Albuquerque,clarissa@exemplo.com,9 7403-4273,Brasil,Ceará,NaN,NaN,Apto 12
59,59,2017-12-03 16:24:32,Stephanie,Freire,stephanie@usuario.com,9 3256-1853,Brasil,São Paulo,Rua 52 do Estado São Paulo,34.0,Apto 24
63,63,2018-05-05 17:52:26,Caíque,Batista,caíque@teste.com,9 8818-5886,Brasil,Ceará,Rua 76 do Estado Ceará,239.0,Apto 19
66,66,2018-10-18 04:31:59,Stephanie,Abreu,stephanie@meu_email.com,9 6466-2389,Brasil,Mato Grosso,Rua 19 do Estado Mato Grosso,53.0,Conjunto 13
68,68,2018-11-14 11:04:35,José,Pires,josé@usuario.com,9 8189-2149,Brasil,Ceará,Avenida 99 do Estado Ceará,231.0,NaN
78,78,2017-11-02 22:13:22,Laura,Queiroz,laura@exemplo.com,9 6338-8617,Brasil,São Paulo,Praça 19 do Estado São Paulo,878.0,Conjunto 3
88,88,2017-10-12 15:17:05,Rafael,Batista,rafael@usuario.com,9 8656-5668,Brasil,Ceará,Rua 78 do Estado Ceará,787.0,Apto 3
98,98,2018-01-24 16:21:06,Cibele,Costa,cibele@meu_email.com,9 4211-6968,Brasil,Mato Grosso,Praça 75 do Estado Mato Grosso,24.0,NaN

In [12]:
tabela['street'] = tabela['street'].fillna('Não Cadastrado')
tabela['email'] = tabela['email'].fillna('Email Não Encontrado')
tabela['number'] = tabela['number'].fillna('Sem Número')
tabela['additionals'] = tabela['additionals'].fillna('Sem Informação')

In [19]:
tabela.head(10)

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,Email Não Encontrado,9 9102-7834,Brasil,Acre,Não Cadastrado,Sem Número,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,Email Não Encontrado,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,Sem Informação
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,Não Cadastrado,Sem Número,Sem Informação
4,4,2018-08-06 07:24:16,Romário,Teixeira,Email Não Encontrado,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
5,5,2018-01-05 17:20:49,Marcelo,Barroso,Email Não Encontrado,9 2830-2088,Brasil,Rio Grande do Sul,Rua 28 do Estado Rio Grande do Sul,805.0,Conjunto 13
6,6,2018-06-18 11:17:42,Cristiano,Elísio,cristiano@exemplo.com,9 3532-8404,Brasil,Goiás,Rua 78 do Estado Goiás,877.0,Apto 14
7,7,2018-02-08 12:36:09,Everton,Barbosa,everton@meu_email.com,9 2553-4087,Brasil,Distrito Federal,Avenida 86 do Estado Distrito Federal,864.0,Apto 14
8,8,2017-12-16 20:47:03,Gabriela,Alves,gabriela@exemplo.com,9 1353-8433,Brasil,Santa Catarina,Não Cadastrado,Sem Número,Sem Informação
9,9,2018-11-11 11:48:41,Luan,Dias,luan@exemplo.com,9 2417-3678,Brasil,Distrito Federal,Avenida 54 do Estado Distrito Federal,889.0,Conjunto 14

In [20]:
tabela['state'] = tabela['state'].replace('São Paulo', 'Sao Paulo')

tabela.head(10)

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,Email Não Encontrado,9 9102-7834,Brasil,Acre,Não Cadastrado,Sem Número,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,Email Não Encontrado,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,Sao Paulo,Avenida 59 do Estado São Paulo,534.0,Sem Informação
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,Não Cadastrado,Sem Número,Sem Informação
4,4,2018-08-06 07:24:16,Romário,Teixeira,Email Não Encontrado,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
5,5,2018-01-05 17:20:49,Marcelo,Barroso,Email Não Encontrado,9 2830-2088,Brasil,Rio Grande do Sul,Rua 28 do Estado Rio Grande do Sul,805.0,Conjunto 13
6,6,2018-06-18 11:17:42,Cristiano,Elísio,cristiano@exemplo.com,9 3532-8404,Brasil,Goiás,Rua 78 do Estado Goiás,877.0,Apto 14
7,7,2018-02-08 12:36:09,Everton,Barbosa,everton@meu_email.com,9 2553-4087,Brasil,Distrito Federal,Avenida 86 do Estado Distrito Federal,864.0,Apto 14
8,8,2017-12-16 20:47:03,Gabriela,Alves,gabriela@exemplo.com,9 1353-8433,Brasil,Santa Catarina,Não Cadastrado,Sem Número,Sem Informação
9,9,2018-11-11 11:48:41,Luan,Dias,luan@exemplo.com,9 2417-3678,Brasil,Distrito Federal,Avenida 54 do Estado Distrito Federal,889.0,Conjunto 14

In [21]:
mapeamento = {'Goiás': 'Goias', 'Piauí': 'Piaui'}
tabela['state'] = tabela['state'].replace(mapeamento)

In [22]:
tabela.head(30)

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,Email Não Encontrado,9 9102-7834,Brasil,Acre,Não Cadastrado,Sem Número,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,Email Não Encontrado,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,Sao Paulo,Avenida 59 do Estado São Paulo,534.0,Sem Informação
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,Não Cadastrado,Sem Número,Sem Informação
4,4,2018-08-06 07:24:16,Romário,Teixeira,Email Não Encontrado,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
5,5,2018-01-05 17:20:49,Marcelo,Barroso,Email Não Encontrado,9 2830-2088,Brasil,Rio Grande do Sul,Rua 28 do Estado Rio Grande do Sul,805.0,Conjunto 13
6,6,2018-06-18 11:17:42,Cristiano,Elísio,cristiano@exemplo.com,9 3532-8404,Brasil,Goias,Rua 78 do Estado Goiás,877.0,Apto 14
7,7,2018-02-08 12:36:09,Everton,Barbosa,everton@meu_email.com,9 2553-4087,Brasil,Distrito Federal,Avenida 86 do Estado Distrito Federal,864.0,Apto 14
8,8,2017-12-16 20:47:03,Gabriela,Alves,gabriela@exemplo.com,9 1353-8433,Brasil,Santa Catarina,Não Cadastrado,Sem Número,Sem Informação
9,9,2018-11-11 11:48:41,Luan,Dias,luan@exemplo.com,9 2417-3678,Brasil,Distrito Federal,Avenida 54 do Estado Distrito Federal,889.0,Conjunto 14
10,10,2017-12-16 15:41:00,Mariana,Alves,mariana@meu_email.com,9 1846-6377,Brasil,Santa Catarina,Não Cadastrado,Sem Número,Sem Informação
11,11,2018-05-16 03:39:52,James,Albuquerque,Email Não Encontrado,9 2430-5905,Brasil,Sergipe,Rua 30 do Estado Sergipe,229.0,Sem Informação
12,12,2018-03-28 00:24:00,Carol,Barboza,carol@exemplo.com,9 8487-3501,Brasil,Mato Grosso,Rua 31 do Estado Mato Grosso,1.0,Conjunto 23
13,13,2018-08-27 21:15:17,Carolina,Monteiro,carolina@teste.com,9 1226-4267,Brasil,Rio Grande do Sul,Rua 4 do Estado Rio Grande do Sul,444.0,Apto 21
14,14,2017-11-12 03:02:41,Francisco,Nascimento,francisco@exemplo.com,9 7264-9020,Brasil,Distrito Federal,Rua 75 do Estado Distrito Federal,47.0,Sem Informação
15,15,2018-11-15 18:00:53,Stephanie,Barbosa,stephanie@usuario.com,9 1446-3560,Brasil,Mato Grosso,Não Cadastrado,Sem Número,Conjunto 4
16,16,2017-12-12 21:29:54,Laura,Santos,laura@exemplo.com,9 7802-6152,Brasil,Maranhão,Rua 57 do Estado Maranhão,213.0,Sem Informação
17,17,2017-10-19 20:18:14,João,Magalhães,joão@exemplo.com,9 5995-1272,Brasil,Pernambuco,Rua 20 do Estado Pernambuco,781.0,Apto 17
18,18,2018-06-28 04:53:52,Jair,Magalhães,jair@exemplo.com,9 8368-1315,Brasil,Alagoas,Avenida 74 do Estado Alagoas,118.0,Conjunto 8
19,19,2018-10-20 19:31:52,Caíque,Monteiro,caíque@exemplo.com,9 9793-9986,Brasil,Piaui,Não Cadastrado,Sem Número,Conjunto 13
20,20,2017-12-22 10:51:28,Adalberto,Silva,adalberto@usuario.com,9 1338-1447,Brasil,Sao Paulo,Rua 57 do Estado São Paulo,851.0,Conjunto 20
21,21,2018-02-21 15:35:55,Diego,Freire,diego@teste.com,9 6686-4094,Brasil,Bahia,Praça 4 do Estado Bahia,906.0,Apto 20
22,22,2018-04-18 22:43:29,Heitor,Pereira,Email Não Encontrado,9 4839-8118,Brasil,Maranhão,Avenida 84 do Estado Maranhão,948.0,Sem Informação
23,23,2017-10-26 00:35:22,Maria,Pires,Email Não Encontrado,9 8229-1067,Brasil,Amazonas,Avenida 80 do Estado Amazonas,581.0,Sem Informação
24,24,2018-07-25 09:34:12,Jair,Barroso,jair@teste.com,9 6679-6120,Brasil,Ceará,Rua 86 do Estado Ceará,770.0,Apto 21
25,25,2018-08-07 12:22:40,Alice,Veloso,alice@exemplo.com,9 9869-3706,Brasil,Minas Gerais,Praça 73 do Estado Minas Gerais,571.0,Sem Informação
26,26,2018-12-12 11:56:14,Eloá,da Silva,eloá@usuario.com,9 3982-5948,Brasil,Espírito Santo,Avenida 98 do Estado Espírito Santo,706.0,Sem Informação
27,27,2018-11-08 11:12:47,Luan,Lima,luan@teste.com,9 2529-8197,Brasil,Acre,Praça 86 do Estado Acre,303.0,Apto 27
28,28,2017-11-26 05:17:39,Beatriz,Araújo,beatriz@usuario.com,9 4543-3853,Brasil,Minas Gerais,Praça 7 do Estado Minas Gerais,536.0,Conjunto 5
29,29,2018-06-03 17:08:52,Geisa,Santos,geisa@meu_email.com,9 4653-9739,Brasil,Rio Grande do Norte,Avenida 77 do Estado Rio Grande do Norte,486.0,Conjunto 13